import { Roboto } from "next/font/google";
import Menu from "@/components/Menu";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin", "greek"],
  weight: ["400", "700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-roboto antialiased flex flex-col bg-black text-white`}>
        <Menu />
        {children}
      </body>
    </html>
  );
}
